### ISSUE TITLE
Trouble compiling "cannot open 'private/async_cu'"

### ISSUE THREAD

**Issue by PMunch** [FedericoCeratto/nim-i3ipc#1]
I installed this through Nimble and copied the sync test into a temporary file. Upon compiling with `nim c -r test.nim` it complains on:
`/home/peter/.nimble/pkgs/i3ipc-0.1.0/i3ipc.nim(16, 15) Error: cannot open 'private/async_cu'`

**Comment by FedericoCeratto** [comment]
Thanks, added.
